spring:

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/shoghlana
    username: root
    password: ${MYSQL_PASSWORD}
    driver-class-name: mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: 'create-drop'
    show-sql: true
    database: MYSQL
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  flyway:
    enabled: true
    locations:
      - classpath:db/migration
    installed-by: "Developer"
    baseline-on-migrate: true
    clean-disabled: true


  application:
    name: backend


## Extensive Logging :
logging:
  level:
    org:
      hibernate:
        type: TRACE
        stat: debug


server:
  port: 8055